# Generated by Django 3.2.4 on 2021-06-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
