# Generated by Django 3.2.4 on 2021-06-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
