# Generated by Django 3.2.4 on 2021-06-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
    ]
