# Generated by Django 3.2.4 on 2021-06-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
