# Generated by Django 3.2.4 on 2021-06-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210613_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='org',
            new_name='user',
        ),
    ]
