# Generated by Django 3.2.4 on 2021-06-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20210614_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='org',
        ),
    ]
