# Generated by Django 3.2.4 on 2021-06-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_user_appointment_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='org',
            new_name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='org_id',
            field=models.IntegerField(default=1),
        ),
    ]
