# Generated by Django 3.2.4 on 2021-06-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20210614_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='org_id',
            field=models.IntegerField(),
        ),
    ]
