# Generated by Django 3.2.4 on 2021-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_appointment_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='org_name',
            field=models.CharField(default='Name', max_length=70),
        ),
    ]
